language: python
python:
- '2.7'
deploy:
  provider: pypi
  user: gholtslander
  password:
    secure: dpKTVvdIi61AGO1BuFljqgw+6MeIaLAi8txSbSsxysLiISc6ijeWbwJGEsJ4r29QVGwW6Gx3GMSiWzWSG5phrF0ySYqpzNun0QST7It6X+dPH5zRPGydeLmul6N4bpYaiJ7Tf3tljedqcB1e+BKS+6Bval0vA8rHlJsuRvuLnyiefMps3U8/Ln7eEwFCNAOjytdgEXcpBBvLDsh0SeJxLktQtZ7+htkGABG/CkozFRtsiTasNvHkwzv4KmAFkWTtx373wH6wl45mlmPrxdRGCELKlrQRNOAo/vUe/1cj0Zq3KnxkOi4V25RSUS30398b31tEwTkTCv9L5hBHzsqVb+QEY5Np3Ok3/qFfOVsuO7/FNuVQXs8+HYItXlDZa2Zvna9iwVTYjSVwfXGQlr7xU2ASnTTGQzml78CT4BztAt2E8zgEwIzVwbwPEy7h8bJ0yqhJ6JaNu/0uPy+ud8o/UVB5W39Invc9fM677iVfw1RR+Vyt/jemKDg8kwG+411O+d0o2UvUt5baMo8k5JGlZEVbSGg/urPjaoLBdrqJOP8NjHbqR6ziBMvy4mL7XrdD2j+t/nKoqtREs9wmVQXYKhs25nKf2UHLg4jxTeF/N09XlsuDpEVnXS1YGfZvetVP2SKC8+vq3l7XVhHNYeicpxe6rrD2dkIHfSBeB6oSwXM=
  on:
    tags: true
script: pytest
